# -*- coding: utf-8 -*-
"""Copy of Fruit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19D4HiThx7k7gxN4iyC53qv-sIlxnb1YF
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install tensorflow opencv-python numpy scikit-learn

import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

DATASET_PATH = "/content/drive/MyDrive/Fruit_Dataset"
print(os.listdir(DATASET_PATH))

DATASET_PATH = "/content/drive/MyDrive/Fruit_Dataset"

IMG_SIZE = 160        # 🔥 REDUCED from 224
BATCH_SIZE = 4        # 🔥 VERY SMALL
EPOCHS = 15

fruit_map = {
    "Apple": 0,
    "Banana": 1,
    "Guava": 2,
    "Orange": 3,
    "Pomegranate": 4,
    "Strawberry": 5
}

fruit_names = list(fruit_map.keys())

day_map = {
    "day1": 5,
    "day2": 4,
    "day3": 3,
    "day4": 2,
    "day5": 1
}

import os
samples = []

for fruit in os.listdir(DATASET_PATH):
    fruit_path = os.path.join(DATASET_PATH, fruit)
    for day in os.listdir(fruit_path):
        day_lower = day.lower()
        day_path = os.path.join(fruit_path, day)
        for img in os.listdir(day_path):
            samples.append((fruit, day_lower, os.path.join(day_path, img)))

print("Total samples:", len(samples))

from tensorflow.keras.utils import Sequence
class FruitGenerator(Sequence):
    def __init__(self, samples):
        self.samples = samples

    def __len__(self):
        return int(np.ceil(len(self.samples) / BATCH_SIZE))

    def __getitem__(self, idx):
        batch = self.samples[idx*BATCH_SIZE:(idx+1)*BATCH_SIZE]

        X, y_fruit, y_fresh, y_days = [], [], [], []

        for fruit, day, path in batch:
            img = cv2.imread(path)
            if img is None:
                continue

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0

            X.append(img)
            y_fruit.append(fruit_map[fruit])
            y_days.append(day_map[day])

            y_fresh.append(0 if day in ["day1","day2","day3"] else 1)

        return np.array(X), {
            "fruit_output": np.array(y_fruit),
            "fresh_output": np.array(y_fresh),
            "days_output": np.array(y_days)
        }

train_gen = FruitGenerator(samples)

import os, cv2, gc
import numpy as np
import tensorflow as tf

from tensorflow.keras.utils import Sequence
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.applications import MobileNetV2

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)

fruit_output = Dense(6, activation="softmax", name="fruit_output")(x)
fresh_output = Dense(1, activation="sigmoid", name="fresh_output")(x)
days_output = Dense(1, activation="linear", name="days_output")(x)

model = Model(
    inputs=base_model.input,
    outputs=[fruit_output, fresh_output, days_output]
)

model.compile(
    optimizer="adam",
    loss={
        "fruit_output": "sparse_categorical_crossentropy",  # fruit name
        "fresh_output": "binary_crossentropy",              # fresh/spoiled
        "days_output": "mse"                                 # shelf life
    },
    metrics={
        "fruit_output": ["accuracy"],
        "fresh_output": ["accuracy"],
        "days_output": ["mse"]
    }
)

model.fit(
    train_gen,
    epochs=EPOCHS
)

gc.collect()

model.save("/content/drive/MyDrive/fruit_shelf_life_model.h5")
print("✅ Model saved to Google Drive")

import os
os.path.exists("/content/drive/MyDrive/fruit_shelf_life_model.h5")

import cv2
import numpy as np
from tensorflow.keras.models import load_model

# Load trained model
model = load_model("/content/drive/MyDrive/fruit_shelf_life_model.h5", compile=False)




fruit_names = ["Apple", "Banana", "Guava", "Orange", "Pomegranate", "Strawberry"]
IMG_SIZE = 160

def predict_fruit(img):
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    fruit_pred, fresh_pred, days_pred = model.predict(img)

    fruit = fruit_names[np.argmax(fruit_pred)]
    freshness = "Fresh" if fresh_pred[0][0] < 0.5 else "Spoiled"
    remaining_days = round(days_pred[0][0], 2)

    return fruit, freshness, remaining_days

!pip install streamlit

# ====== MOUNT DRIVE ======
from google.colab import drive
drive.mount('/content/drive')

# ====== IMPORTS ======
import cv2
import numpy as np
from google.colab import files
from tensorflow.keras.models import load_model
from IPython.display import display, Javascript
from google.colab.patches import cv2_imshow
import base64

# ====== LOAD MODEL ======
model = load_model(
    "/content/drive/MyDrive/fruit_shelf_life_model.h5",
    compile=False
)

fruit_names = ["Apple", "Banana", "Guava", "Orange", "Pomegranate", "Strawberry"]
IMG_SIZE = 160

# ====== PREDICTION FUNCTION ======
def predict_fruit(img):
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    fruit_pred, fresh_pred, days_pred = model.predict(img)

    fruit = fruit_names[np.argmax(fruit_pred)]
    freshness = "fresh" if fresh_pred[0][0] < 0.5 else "spoiled"
    days = round(days_pred[0][0], 2)

    print("\n🔎 Prediction Result")
    print("----------------------")
    print("Fruit           :", fruit)
    print("Freshness       :", freshness)
    print("Remaining Days  :", days)

# ====== CAMERA FUNCTION (FIXED) ======
def take_photo(filename='camera_capture.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
          const div = document.createElement('div');
          const button = document.createElement('button');
          button.textContent = '📸 Capture';
          div.appendChild(button);

          const video = document.createElement('video');
          video.style.display = 'block';
          const stream = await navigator.mediaDevices.getUserMedia({video: true});
          document.body.appendChild(div);
          div.appendChild(video);
          video.srcObject = stream;
          await video.play();

          await new Promise((resolve) => button.onclick = resolve);

          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          canvas.getContext('2d').drawImage(video, 0, 0);
          stream.getTracks()[0].stop();
          div.remove();

          return canvas.toDataURL('image/jpeg', quality);
        }
        ''')
    display(js)

    data = display(Javascript('takePhoto({})'.format(quality)))

# ====== MENU ======
print("\n==============================")
print("     Fruit Shelf Life Predictor")
print("==============================\n")
print("1  Camera Capture")
print("2  Upload Image")

choice = input("\nEnter 1 or 2: ")

# ====== CAMERA OPTION ======
if choice == "1":
    print("\n📸 Opening camera...")
    take_photo()

    # Convert captured image to file
    image_base64 = input("\nPaste the BASE64 output here and press Enter:\n")
    image_bytes = base64.b64decode(image_base64.split(',')[1])

    with open("camera_capture.jpg", "wb") as f:
        f.write(image_bytes)

    img = cv2.imread("camera_capture.jpg")
    print("Captured Image")
    cv2_imshow(img)

    predict_fruit(img)

# ====== UPLOAD OPTION ======
elif choice == "2":
    uploaded = files.upload()
    for file_name in uploaded.keys():
        img = cv2.imread(file_name)
        print("Uploaded Image")
        cv2_imshow(img)
        predict_fruit(img)

else:
    print("❌ Invalid choice")

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
from google.colab import files
from tensorflow.keras.models import load_model
from google.colab.patches import cv2_imshow

# Load model
model = load_model(
    "/content/drive/MyDrive/fruit_shelf_life_model.h5",
    compile=False
)

fruit_names = ["Apple", "Banana", "Guava", "Orange", "Pomegranate", "Strawberry"]
IMG_SIZE = 160

def predict_fruit(img):
    img_resized = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img_resized = img_resized / 255.0
    img_resized = np.expand_dims(img_resized, axis=0)

    fruit_pred, fresh_pred, days_pred = model.predict(img_resized)

    fruit = fruit_names[np.argmax(fruit_pred)]
    freshness = "fresh" if fresh_pred[0][0] < 0.5 else "spoiled"
    days = round(days_pred[0][0], 2)

    print("\n🔎 Prediction Result")
    print("----------------------")
    print("Fruit           :", fruit)
    print("Freshness       :", freshness)
    print("Remaining Days  :", days)

# Upload image
uploaded = files.upload()

for file_name in uploaded.keys():
    img = cv2.imread(file_name)

    # Show SMALL image
    display_img = cv2.resize(img, (300, 300))
    print("Uploaded Image")
    cv2_imshow(display_img)

    predict_fruit(img)

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
from google.colab import files
from tensorflow.keras.models import load_model
from google.colab.patches import cv2_imshow
def predict_fruit(img):
    img_resized = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img_resized = img_resized / 255.0
    img_resized = np.expand_dims(img_resized, axis=0)

    fruit_pred, fresh_pred, days_pred = model.predict(img_resized)

    fruit_confidence = float(np.max(fruit_pred))
    fruit_index = int(np.argmax(fruit_pred))

    CONFIDENCE_THRESHOLD = 0.8   # 🔥 stricter threshold

    print("\n🔎 Prediction Result")
    print("----------------------")

    if fruit_confidence < CONFIDENCE_THRESHOLD:
        print("Fruit           : Unknown")
        print("Quality         : Not applicable")
        print("Remaining Days  : Not applicable")
        print("Confidence      :", round(fruit_confidence, 2))
        return

    fruit = fruit_names[fruit_index]

    freshness_score = float(fresh_pred[0][0])
    if freshness_score < 0.3:
        quality = "Fresh"
    elif freshness_score < 0.6:
        quality = "Semi-Fresh"
    else:
        quality = "Spoiled"

    days = round(float(days_pred[0][0]), 2)

    print("Fruit           :", fruit)
    print("Quality         :", quality)
    print("Remaining Days  :", days)
    print("Confidence      :", round(fruit_confidence, 2))

uploaded = files.upload()

for file_name in uploaded.keys():
    img = cv2.imread(file_name)

    print("\n📷 Uploaded Image")
    display_img = cv2.resize(img, (300, 300))
    cv2_imshow(display_img)

    predict_fruit(img)

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error

DATASET_PATH = "/content/drive/MyDrive/Fruit_Dataset"
IMG_SIZE = 160
SAMPLES_PER_CLASS = 50

y_true = []
y_pred = []

for fruit in os.listdir(DATASET_PATH):
    fruit_path = os.path.join(DATASET_PATH, fruit)
    count = 0

    for day_folder in os.listdir(fruit_path):
        day_path = os.path.join(fruit_path, day_folder)
        true_day = int(day_folder.lower().replace("day", ""))

        for img_name in os.listdir(day_path):
            if count >= SAMPLES_PER_CLASS:
                break

            img = cv2.imread(os.path.join(day_path, img_name))
            if img is None:
                continue

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0
            img = np.expand_dims(img, axis=0)

            _, _, day_pred = model.predict(img, verbose=0)

            y_true.append(true_day)
            y_pred.append(day_pred[0][0])
            count += 1

        if count >= SAMPLES_PER_CLASS:
            break

y_true = np.array(y_true)
y_pred = np.array(y_pred)

mae = mean_absolute_error(y_true, y_pred)

print("MAE (Mean Absolute Error):", round(mae, 3))

# Scatter plot (correct for regression)
plt.figure(figsize=(6, 4), dpi=120)
plt.scatter(y_true, y_pred, alpha=0.6)
plt.plot([1, 5], [1, 5], 'r--')

plt.xlabel("Actual Shelf Life (Days)")
plt.ylabel("Predicted Shelf Life (Days)")
plt.title(f"Shelf Life Prediction (MAE = {mae:.2f} Days)")
plt.tight_layout()
plt.show()

import os
import cv2
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# CONFIG
DATASET_PATH = "/content/drive/MyDrive/Fruit_Dataset"
IMG_SIZE = 160
SAMPLES_PER_DAY = 10

freshness_labels = ["Fresh", "Semi-Fresh", "Spoiled"]

def shelf_to_freshness(day):
    if day <= 2:
        return 0   # Fresh
    elif day == 3:
        return 1   # Semi-Fresh
    else:
        return 2   # Spoiled

y_true = []
y_pred = []

for fruit in ["Apple", "Banana", "Guava", "Orange", "Pomegranate", "Strawberry"]:
    fruit_path = os.path.join(DATASET_PATH, fruit)

    for day_folder in ["Day1", "Day2", "Day3", "Day4", "Day5"]:
        day_path = os.path.join(fruit_path, day_folder)
        true_day = int(day_folder.replace("Day", ""))

        count = 0
        for img_name in os.listdir(day_path):
            if count >= SAMPLES_PER_DAY:
                break

            img = cv2.imread(os.path.join(day_path, img_name))
            if img is None:
                continue

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0
            img = np.expand_dims(img, axis=0)

            _, _, day_pred = model.predict(img, verbose=0)
            predicted_day = round(day_pred[0][0])

            y_true.append(shelf_to_freshness(true_day))
            y_pred.append(shelf_to_freshness(predicted_day))

            count += 1

# FORCE 3×3 MATRIX
cm = confusion_matrix(y_true, y_pred, labels=[0,1,2])

# PLOT
plt.figure(figsize=(4.5, 3.5), dpi=120)
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=freshness_labels,
    yticklabels=freshness_labels,
    cbar=False
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix – Shelf-Life Categories")
plt.tight_layout()
plt.show()

print("Total samples:", len(y_true))

import numpy as np

categories = {0: [], 1: [], 2: []}  # Fresh, Semi-Fresh, Spoiled

def shelf_to_freshness(day):
    if day <= 2:
        return 0
    elif day == 3:
        return 1
    else:
        return 2

for true_day, pred_day in zip(y_true, y_pred):
    true_cat = shelf_to_freshness(true_day)
    categories[true_cat].append(abs(true_day - pred_day))

print("MAE by Shelf-Life Category:")

labels = ["Fresh", "Semi-Fresh", "Spoiled"]
for i, label in enumerate(labels):
    if len(categories[i]) > 0:
        print(f"{label}: {round(np.mean(categories[i]), 2)}")
    else:
        print(f"{label}: Not enough samples")

import os
import cv2
import numpy as np
from sklearn.metrics import classification_report

# CONFIG
DATASET_PATH = "/content/drive/MyDrive/Fruit_Dataset"
IMG_SIZE = 160
SAMPLES_PER_DAY = 10

fruit_names = ["Apple", "Banana", "Guava", "Orange", "Pomegranate", "Strawberry"]
freshness_labels = ["Fresh", "Semi-Fresh", "Spoiled"]

# Shelf-life → Freshness category
def shelf_to_freshness(day):
    if day <= 2:
        return 0   # Fresh
    elif day == 3:
        return 1   # Semi-Fresh
    else:
        return 2   # Spoiled

y_true = []
y_pred = []

# DATA LOOP
for fruit in fruit_names:
    fruit_path = os.path.join(DATASET_PATH, fruit)

    for day_folder in ["Day1", "Day2", "Day3", "Day4", "Day5"]:
        day_path = os.path.join(fruit_path, day_folder)
        true_day = int(day_folder.replace("Day", ""))

        count = 0
        for img_name in os.listdir(day_path):
            if count >= SAMPLES_PER_DAY:
                break

            img = cv2.imread(os.path.join(day_path, img_name))
            if img is None:
                continue

            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0
            img = np.expand_dims(img, axis=0)

            # Predict shelf life
            _, _, day_pred = model.predict(img, verbose=0)
            predicted_day = round(day_pred[0][0])

            y_true.append(shelf_to_freshness(true_day))
            y_pred.append(shelf_to_freshness(predicted_day))

            count += 1

# CLASSIFICATION REPORT
print("\nFINAL METRICS REPORT – SHELF LIFE CATEGORIES\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=freshness_labels,
    digits=2
))

from tensorflow.keras.models import load_model

model = load_model(
    "/content/drive/MyDrive/fruit_shelf_life_model.h5",
    compile=False
)

print("✅ Model loaded successfully")